/*
 * mathematics.h
 *
 *  Created on: Jun 9, 2024
 *      Author: João Pedro
 */

#ifndef MATHEMATICS_H_
#define MATHEMATICS_H_

#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdint.h>

// Generated by Google Gemini
float max(float* arr, uint16_t size);
float maxStartEnd(float* arr, uint16_t start, uint16_t end);
uint16_t indexMax(float* arr, uint16_t size);
int compareInts(const void* a, const void* b);
uint16_t lowerBound(uint32_t* arr, uint16_t size, uint32_t lower_bound);
uint16_t upperBound(uint32_t* arr, uint16_t size, uint32_t upper_bound);
void findValuesInRange(uint32_t* arr, uint32_t size, uint32_t lower_bound, uint32_t upper_bound, uint8_t* result_len, uint32_t* result);
float mean(float* arr, uint16_t array_size);
uint16_t append5(float* array, uint16_t array_size, float value);
uint16_t append_ms350(float* array, uint16_t array_size, float value);

#endif /* MATHEMATICS_H */
